version: '3'
services:
#REDIS
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"

#POSTGRES
  postgres:
      image: postgres:latest
      environment:
        POSTGRES_DB: topcbr
        POSTGRES_USER: topcbr
        POSTGRES_PASSWORD: topcbr
#        PGDATA: /data/postgres
#      volumes:
#         - /data/postgres:/data/postgres
      ports:
        - "5432:5432"
      restart: unless-stopped

#NATS
  nats:
      image: nats:latest
      command:
            - "-D"
            - "-p"
            - "4222"
            - "-m"
            - "8222"
      ports:
        - "8222:8222"
        - "6222:6222"
        - "4222:4222"
      restart: unless-stopped