[DbCreds]
serverDev = "host=127.0.0.1 dbname=postgres sslmode=disable port=32768 user=postgres password=1"
serverProd = "host=127.0.0.1 dbname=postgres sslmode=disable port=5432 user=postgres password=V4;qxjfY84NRx{nZ3}TFBjMH)"

[SecretKey]
key = "%kxkstXG%@uEG4^fj_gt8*XK?tzG@ddY#+wAd"

[Consul]
addressDev = "http://127.0.0.1:8500"
addressProd = "http://194.87.236.106:8500"

[services]
vault = "vaultsvc"
registration = "regsvc"
auth = "authsvc"
tcal = "tcalsvc"

[tags]
tag = "Adexin"