[DbCreds]
server = "root:1@tcp(localhost:3306)/TaskCalendarDb"

[SecretKey]
key = "%kxkstXG%@uEG4^fj_gt8*XK?tzG@ddY#+wAd"

[Consul]
address = "http://127.0.0.1:8500"

[services]
vault = "vaultsvc"
registration = "regsvc"

[tags]
tag = "Adexin"